#!/usr/bin/env python3
"""Convert beybeetle-splash.png to a 240x240 RGB565 C header (byte-swapped for g_fb).

The source PNG is a silhouette: transparent background, solid (black) artwork.
Source RGB is ignored — the alpha channel is the mask. Alpha 0 becomes the
EVA Unit 01 background purple, alpha 255 becomes the neon green; partial alpha
blends between the two so an antialiased PNG still converts cleanly.
"""
import os
import numpy as np
from PIL import Image

PNG_IN  = os.path.join(os.path.dirname(__file__), '../assets/splash/beybeetle-splash.png')
OUT_H   = os.path.join(os.path.dirname(__file__), '../src/splash_image.h')

BG_RGB = (0x76, 0x58, 0x98)   # dark violet body #765898 — COLOR_DPURP
FG_RGB = (0x52, 0xD0, 0x53)   # neon green energy #52d053 — COLOR_NGRE

img = Image.open(PNG_IN).convert('RGBA').resize((240, 240), Image.NEAREST)

# Blend FG over BG using alpha as the mask (source RGB discarded)
a  = np.array(img, dtype=np.float32)[:, :, 3] / 255.0
bg = np.array(BG_RGB, dtype=np.float32).reshape(1, 1, 3)
fg = np.array(FG_RGB, dtype=np.float32).reshape(1, 1, 3)
px = (fg * a[:, :, None] + bg * (1.0 - a[:, :, None]))
px = np.clip(px + 0.5, 0, 255).astype(np.uint16)

r = px[:, :, 0] >> 3
g = px[:, :, 1] >> 2
b = px[:, :, 2] >> 3
rgb565 = (r << 11) | (g << 5) | b

# byte-swap to match g_fb storage (DMA_SIZE_8, __builtin_bswap16)
swapped = ((rgb565 & 0xFF) << 8) | (rgb565 >> 8)

flat = swapped.flatten()
with open(OUT_H, 'w') as f:
    f.write('#pragma once\n#include <stdint.h>\n\n')
    f.write('// beybeetle-splash.png 240x240 RGB565 byte-swapped (g_fb format)\n')
    f.write('// Generated by tools/convert_splash.py — alpha mask recoloured:\n')
    f.write('//   background #%02X%02X%02X (COLOR_DPURP) / artwork #%02X%02X%02X (COLOR_NGRE)\n'
            % (*BG_RGB, *FG_RGB))
    f.write('static const uint16_t splash_image[240*240] = {\n')
    for i in range(0, len(flat), 16):
        chunk = flat[i:i+16]
        f.write('    ' + ', '.join(f'0x{v:04X}' for v in chunk) + ',\n')
    f.write('};\n')

print(f'Splash: 240x240, {len(flat)*2} bytes')
print(f'  bg #{BG_RGB[0]:02X}{BG_RGB[1]:02X}{BG_RGB[2]:02X} -> 0x{swapped[0,0]:04X} (swapped)')
print(f'Written: {OUT_H}')
